name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.18.0' # Specify your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Package the application
      - name: Package application files
        run: zip -r app.zip .  # Compress the files into a zip file

      # Step 6: Upload to S3 (optional for storing build artifacts)
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp app.zip s3://461group21bucket/app.zip --region us-east-2
          if [ $? -ne 0 ]; then
            echo "S3 upload failed"
            exit 1
          fi
          echo "S3 upload succeeded"
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
        run: |
          # Create the EC2 key file
          echo "${{ secrets.EC2_KEY }}" > /tmp/key.pem
          chmod 600 /tmp/key.pem
      
          # Transfer the zip file to the EC2 instance
          scp -i /tmp/key.pem -o "StrictHostKeyChecking=no" app.zip $EC2_USER@$EC2_HOST:/home/$EC2_USER/app.zip
          if [ $? -ne 0 ]; then
            echo "File transfer failed"
            exit 1
          fi
          echo "File transfer succeeded"

          # Check if the file exists directly on EC2
          ssh -i /tmp/key.pem -o "StrictHostKeyChecking=no" $EC2_USER@$EC2_HOST "ls -l /home/$EC2_USER/app.zip"

          # SSH into the EC2 instance and deploy the app
          ssh -i /tmp/key.pem -o "StrictHostKeyChecking=no" $EC2_USER@$EC2_HOST << EOF
            # Install Node.js 20.18.0
            curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo bash -
            sudo yum install -y nodejs unzip
            sudo yum install -y nc
            sudo npm install -g pm2
            sudo yum install -y postgresql
          
            # Check if app.zip exists and unzip
            if [ -f "/home/$EC2_USER/app.zip" ]; then
              echo "app.zip found. Unzipping..."
              unzip -o /home/$EC2_USER/app.zip -d /home/$EC2_USER/app
            else
              echo "app.zip not found!"
              exit 1
            fi
          
            # Navigate to the backend/dist directory
            cd /home/$EC2_USER/app/backend/dist || exit 1
            
            # List files to confirm presence of server.js
            
            # Update and install PostgreSQL client
            sudo yum update -y
            sudo amazon-linux-extras enable postgresql14
            sudo yum install -y postgresql
            
            # Verify psql installation
            psql --version
            
            # Test manual DB connection
            echo "manually connect"
            PGPASSWORD=$DB_PASS psql -h $DB_HOST -U $DB_USER -d $DB_NAME -c "\dt"
            echo "end manual connect"

            export DB_NAME=${DB_NAME}
            export DB_USER=${DB_USER}
            export DB_PASS=${DB_PASS}
            export DB_HOST=${DB_HOST}
            echo "DB_NAME is set to $DB_NAME"
            echo "DB_USER is set to $DB_USER"
            echo "DB_HOST is set to $DB_HOST"

            echo "testing ec2 db conn"
            nc -zv $DB_HOST 5432
            echo "end test"
            #bruh

            # Install dependencies
            echo "Installing dependencies..."
            npm install
          
           # echo "Starting the application..."
            node server.js

          EOF

